name = "workaround"
version = "0.1.0"
defaultTargets = ["workaround"]

[[lean_lib]]
name = "Workaround"

[[require]]
name = "doc-gen4"
git = "https://github.com/Vierkantor/doc-gen4"
rev = "importAll"

[[require]]
name = "mathlib"
path = "../mathlib4"
